name: Tests 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  tests:
    name: Tests 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    - name: Bundle install 
      run: |
        cd Sources/PhotoUploader && bundle install
        
    - name: Run tests 
      run: |
        cd Sources/PhotoUploader && bundle exec fastlane tests